# Generated by Django 6.0 on 2026-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_uploadcoursedocuments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ManyToManyField(
                        related_name="classes", to="academics.course"
                    ),
                ),
            ],
        ),
    ]
