# Generated by Django 6.0 on 2026-02-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.RenameField(
            model_name="class",
            old_name="description",
            new_name="learning_objectives",
        ),
    ]
